import React, { useEffect, useState } from 'react'
import { useDispatch } from 'react-redux';
import {CSSTransition} from 'react-transition-group'; // ES6
import getOne from './messagesStore'


export default function Home() {
    const [display, setDisplay] = useState(false);
    const dispatch = useDispatch();

    useEffect(() => {
        setDisplay(true);
    })

    const clickhandler = (event) => {
        // console.log(event.target.attributes.name.value)
        dispatch({
            type: 'MESSAGE',
            payload: getOne(event.target.attributes.name.value)
        })
    }

    return (
        <CSSTransition in={display} timeout={2000} classNames="my-node">
        <div className='projects'>
        <h1>PROJECTS</h1>
        <div className='project'>
            <h3 name='foodapp' onClick={clickhandler}>FOOD APP 🍓</h3>
            <p>An app to control the amount of calories that you absorb.</p>
        </div>
        <div className='project' >
            <h3 name='todolist' onClick={clickhandler}>TODO LIST 📝</h3>
            <p>Using this app gives you an opportunity to manage your tasks easily. Even after closing browser, your unfinished tasks still will be displayed.</p>
        </div>
        <div className='project' >
            <h3 name='mazeapp' onClick={clickhandler}>MAZE APP 🧩</h3>
            <p>There is a maze. You can find a route for a mouse to the exit by pressing 'Find path' button if the path exists.
            Also, a new maze can be generated by pressing 'Generate button'.</p>
        </div>
        <div className='project' >
            <h3 name='countries' onClick={clickhandler}>COUNTRIES 🌍</h3>
            <p>The service has home page and countries section, where you can 
            take a look at the variety of different countries (its name, the capital, continental affilation, population and flag).</p>
        </div>
        <div className='project' name='bookdirectory' onClick={clickhandler}>
            <h3 name='bookdirectory' onClick={clickhandler}>BOOK DIRECTORY 📚</h3>
            <p>The app allows you store information about books. You can: load whole libriary, add new staff, edit existing book using id of the book to search it,
            delete the one you don't need anymore.</p>
        </div>
        
    </div>
    </CSSTransition>
  )
}
